use demodb;
alter table student
add column city varchar(255);
UPDATE student SET city = 'Delhi' WHERE roll = 1;
UPDATE student SET city = 'Noida' WHERE roll = 2;
UPDATE student SET city = 'Gurgaon' WHERE roll = 3;
UPDATE student SET city = 'Jaipur' WHERE roll = 4;
UPDATE student SET city = 'Kanpur' WHERE roll = 5;
UPDATE student SET city = 'Bhopal' WHERE roll = 6;
UPDATE student SET city = 'Hyderabad' WHERE roll = 7;
UPDATE student SET city = 'Mumbai' WHERE roll = 8;
UPDATE student SET city = 'Delhi' WHERE roll = 9;
UPDATE student SET city = 'Ahmedabad' WHERE roll = 10;
UPDATE student SET city = 'Navi Mumbai' WHERE roll = 11;
UPDATE student SET city = 'Bangalore' WHERE roll = 12;
UPDATE student SET city = 'Delhi' WHERE roll = 13;
UPDATE student SET city = 'Mumbai' WHERE roll = 14;
UPDATE student SET city = 'Delhi' WHERE roll = 15;
UPDATE student SET city = 'Chennai' WHERE roll = 16;
UPDATE student SET city = 'Delhi' WHERE roll = 17;
UPDATE student SET city = 'Bangalore' WHERE roll = 18;
UPDATE student SET city = 'Kanpur' WHERE roll = 19;
UPDATE student SET city = 'Delhi' WHERE roll = 20;
UPDATE student SET city = 'Delhi' WHERE roll = 21;
UPDATE student SET city = 'Delhi' WHERE roll = 22;
UPDATE student SET city = 'Mumbai' WHERE roll = 23;
UPDATE student SET city = 'Hyderabad' WHERE roll = 24;
UPDATE student SET city = 'Hyderabad' WHERE roll = 25;
UPDATE student SET city = 'Hyderabad' WHERE roll = 26;
UPDATE student SET city = 'Delhi' WHERE roll = 27;
UPDATE student SET city = 'Delhi' WHERE roll = 28;
UPDATE student SET city = 'Noida' WHERE roll = 29;
UPDATE student SET city = 'Noida' WHERE roll = 30;
UPDATE student SET city = 'Delhi' WHERE roll = 31;
UPDATE student SET city = 'Delhi' WHERE roll = 32;
UPDATE student SET city = 'Delhi' WHERE roll = 33;
UPDATE student SET city = 'Delhi' WHERE roll = 34;
UPDATE student SET city = 'Delhi' WHERE roll = 35;
UPDATE student SET city = 'Delhi' WHERE roll = 36;
UPDATE student SET city = 'Delhi' WHERE roll = 37;
UPDATE student SET city = 'Delhi' WHERE roll = 38;
UPDATE student SET city = 'Delhi' WHERE roll = 39;
UPDATE student SET city = 'Delhi' WHERE roll = 40;
UPDATE student SET city = 'Delhi' WHERE roll = 41;
UPDATE student SET city = 'Noida' WHERE roll = 42;
UPDATE student SET city = 'Ayodhya' WHERE roll = 43;
UPDATE student SET city = 'Ayodhya' WHERE roll = 44;

